RSDK-5032 - strip authentity of protocol string
viamrobotics/viam-typescript-sdk pull request #166
Opened 2023-09-28 17:42 UTC by purplenicole730

2023-09-28 17:50 UTC, maximpertsov commented on src/robot/dial.ts
> +  conf.authEntity = conf.authEntity?.replace(/^(?<http>.*:\/\/)/u, '');
let's use the built-in URL parser to get the host

```suggestion
  if (conf.authEntity) {
    conf.authEntity = new URL(conf.authEntity).host;
  }
```

2023-09-28 17:51 UTC, maximpertsov requested changes
in addition to the suggestion, can you leave a note about how this was tested?

2023-09-28 18:16 UTC, purplenicole730 commented
> in addition to the suggestion, can you leave a note about how this was tested?

@maximpertsov What do you mean? Do you want me to say that the change was tested by replacing the vanilla `main`?

2023-09-28 18:25 UTC, maximpertsov commented
> > in addition to the suggestion, can you leave a note about how this was tested?
> 
> @maximpertsov What do you mean? Do you want me to say that the change was tested by replacing the vanilla `main` with my own laptop as the local robot?

yeah, any details about the scripts your ran, the setup, etc would be helpful

2023-09-29 15:34 UTC, maximpertsov approved these changes

2023-09-29 15:35 UTC, merged